# Barra de estado — modo CLARO (Flexoki, papel cálido)
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#e6e4d9,fg=#6f6e69"
set -g status-left "#[bg=#205ea6,fg=#fffcf0,bold] #S #[bg=#e6e4d9,fg=#205ea6] "
set -g status-left-length 30
set -g window-status-format "#[fg=#6f6e69] #I #W "
set -g window-status-current-format "#[bg=#dad8ce,fg=#205ea6,bold] #I #W "
# el #(...continuum_save.sh) mantiene vivo el auto-guardado de sesiones
set -g status-right "#[fg=#205ea6] %H:%M #[fg=#6f6e69] %d-%b #(~/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)"
set -g status-right-length 60
set -g pane-border-style "fg=#dad8ce"
set -g pane-active-border-style "fg=#205ea6"
set -g message-style "bg=#205ea6,fg=#fffcf0"
set -g mode-style "bg=#205ea6,fg=#fffcf0"
