# Barra de estado — modo OSCURO (Tokyo Night)
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#1a1b26,fg=#a9b1d6"
set -g status-left "#[bg=#7aa2f7,fg=#1a1b26,bold] #S #[bg=#1a1b26,fg=#7aa2f7] "
set -g status-left-length 30
set -g window-status-format "#[fg=#565f89] #I #W "
set -g window-status-current-format "#[bg=#292e42,fg=#7aa2f7,bold] #I #W "
# el #(...continuum_save.sh) mantiene vivo el auto-guardado de sesiones
set -g status-right "#[fg=#7aa2f7] %H:%M #[fg=#565f89] %d-%b #(~/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)"
set -g status-right-length 60
set -g pane-border-style "fg=#292e42"
set -g pane-active-border-style "fg=#7aa2f7"
set -g message-style "bg=#7aa2f7,fg=#1a1b26"
set -g mode-style "bg=#7aa2f7,fg=#1a1b26"
